/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthComplex;

import healthComplex.MenuPage;
import healthComplex.WelcomePage;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class LogInPage extends javax.swing.JFrame {

    /**
     * Creates new form LogInPage
     */
    public LogInPage() {
        initComponents();
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserIdMsg1 = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblBangladeshHealthComplexMsg = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btBack = new javax.swing.JButton();
        btLogIn = new javax.swing.JButton();
        lblPasswordLogo = new javax.swing.JLabel();
        lblUseIdLogo = new javax.swing.JLabel();
        lblBlindLogo = new javax.swing.JLabel();
        lblEyeLogo = new javax.swing.JLabel();
        btReset = new javax.swing.JButton();
        lblWelcomePageBackground = new javax.swing.JLabel();

        lblUserIdMsg1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblUserIdMsg1.setText("Enter User ID");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserID.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblUserID.setForeground(new java.awt.Color(153, 153, 153));
        lblUserID.setText(" User ID");
        getContentPane().add(lblUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 100, 50));

        lblPassword.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 153, 153));
        lblPassword.setText(" Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 110, 50));

        lblBangladeshHealthComplexMsg.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblBangladeshHealthComplexMsg.setText("Bangladesh Health Complex");
        getContentPane().add(lblBangladeshHealthComplexMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 600, 100));

        txtUserID.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserIDKeyTyped(evt);
            }
        });
        getContentPane().add(txtUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 300, 50));

        txtPassword.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 300, 50));

        btBack.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/back logo.png"))); // NOI18N
        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        getContentPane().add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 150, 50));

        btLogIn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/login logo.png"))); // NOI18N
        btLogIn.setText("Log In");
        btLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogInActionPerformed(evt);
            }
        });
        getContentPane().add(btLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 150, 50));

        lblPasswordLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/password logo.png"))); // NOI18N
        getContentPane().add(lblPasswordLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 60, 50));

        lblUseIdLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/user id logo.png"))); // NOI18N
        getContentPane().add(lblUseIdLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 60, 50));

        lblBlindLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/blind logo.png"))); // NOI18N
        lblBlindLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBlindLogoMouseClicked(evt);
            }
        });
        getContentPane().add(lblBlindLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 50, 50));

        lblEyeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/eye logo.png"))); // NOI18N
        lblEyeLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEyeLogoMouseClicked(evt);
            }
        });
        getContentPane().add(lblEyeLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 50, 50));

        btReset.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/reset logo.png"))); // NOI18N
        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        getContentPane().add(btReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 150, 50));

        lblWelcomePageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/Background2.jpg"))); // NOI18N
        getContentPane().add(lblWelcomePageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblEyeLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEyeLogoMouseClicked
        lblEyeLogo.setVisible(false);
        lblBlindLogo.setVisible(true);
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_lblEyeLogoMouseClicked

    private void lblBlindLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBlindLogoMouseClicked
        lblBlindLogo.setVisible(false);
        lblEyeLogo.setVisible(true);
        txtPassword.setEchoChar((char)0);
    }//GEN-LAST:event_lblBlindLogoMouseClicked

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        if(txtUserID.getText().isEmpty()&&txtPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"To reset fill the fields first..");
        }
        else{
            txtUserID.setText("  ");
            txtPassword.setText(null);
        }
    }//GEN-LAST:event_btResetActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        setVisible(false);
        WelcomePage w = new WelcomePage();
        w.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogInActionPerformed

        if(txtUserID.getText().isEmpty()||txtPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter User ID and  Password...");
        }
        else if(txtUserID.getText().equals("Bangladesh")&&txtPassword.getText().equals("SJPCNP123")){
            setVisible(false);
            MenuPage m = new MenuPage();
            m.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Incorrect User ID or  Password , Try again...");
            txtUserID.setText("  ");
            txtPassword.setText(null);
        }

    }//GEN-LAST:event_btLogInActionPerformed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        lblPassword.setVisible(false);
        if(txtPassword.getText().isEmpty()){
            lblPassword.setVisible(true);
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtUserIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIDKeyTyped
        lblUserID.setVisible(false);
        if(txtUserID.getText().isEmpty()){
            lblUserID.setVisible(true);
        }
    }//GEN-LAST:event_txtUserIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btLogIn;
    private javax.swing.JButton btReset;
    private javax.swing.JLabel lblBangladeshHealthComplexMsg;
    private javax.swing.JLabel lblBlindLogo;
    private javax.swing.JLabel lblEyeLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordLogo;
    private javax.swing.JLabel lblUseIdLogo;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserIdMsg1;
    private javax.swing.JLabel lblWelcomePageBackground;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
