/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthComplex;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LogOutPage extends javax.swing.JFrame {

    /**
     * Creates new form LogOutPage
     */
    public LogOutPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogOutPage = new javax.swing.JPanel();
        lblLogOutQuestion = new javax.swing.JLabel();
        btYes = new javax.swing.JButton();
        btNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogOutPage.setBackground(new java.awt.Color(153, 204, 255));

        lblLogOutQuestion.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblLogOutQuestion.setText("Are you sure ??");

        btYes.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        btYes.setText("Yes");
        btYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYesActionPerformed(evt);
            }
        });

        btNo.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        btNo.setText("No");
        btNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLogOutPageLayout = new javax.swing.GroupLayout(panelLogOutPage);
        panelLogOutPage.setLayout(panelLogOutPageLayout);
        panelLogOutPageLayout.setHorizontalGroup(
            panelLogOutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogOutPageLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(lblLogOutQuestion)
                .addGap(63, 63, 63))
            .addGroup(panelLogOutPageLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btYes)
                .addGap(26, 26, 26)
                .addComponent(btNo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelLogOutPageLayout.setVerticalGroup(
            panelLogOutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogOutPageLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblLogOutQuestion)
                .addGap(31, 31, 31)
                .addGroup(panelLogOutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btYes)
                    .addComponent(btNo))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogOutPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogOutPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYesActionPerformed
        JOptionPane.showMessageDialog(this,"Logging Out...");
        setVisible(false);
        MenuPage m = new MenuPage();
        m.setVisible(false);
        LogInPage l = new LogInPage();
        l.setVisible(true);
    }//GEN-LAST:event_btYesActionPerformed

    private void btNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogOutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogOutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogOutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogOutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogOutPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNo;
    private javax.swing.JButton btYes;
    private javax.swing.JLabel lblLogOutQuestion;
    private javax.swing.JPanel panelLogOutPage;
    // End of variables declaration//GEN-END:variables
}
