/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthComplex;

/**
 *
 * @author User
 */
public class ManageInformationPage extends javax.swing.JFrame {

    /**
     * Creates new form ManageInformationPage
     */
    public ManageInformationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBangladeshHealthComplexMsg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMedicalRecord1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMedicalRecord2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblMedicalRecord = new javax.swing.JLabel();
        panelPersonalInformation = new javax.swing.JPanel();
        lblPersonalInformation = new javax.swing.JLabel();
        lblPatientFirstName = new javax.swing.JLabel();
        lblPatientLastName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPatientLastName = new javax.swing.JTextField();
        txtPatientFirstName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtlAge = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        RbtMale = new javax.swing.JRadioButton();
        rbtFemale = new javax.swing.JRadioButton();
        btSearchBox = new javax.swing.JButton();
        lblSearchBox = new javax.swing.JLabel();
        txtSearchBox = new javax.swing.JTextField();
        lblNoteMsg = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        lblWelcomePageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBangladeshHealthComplexMsg.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblBangladeshHealthComplexMsg.setText("Bangladesh Health Complex");
        getContentPane().add(lblBangladeshHealthComplexMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 600, 100));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblMedicalRecord1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblMedicalRecord1.setText("Operation Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblMedicalRecord1)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedicalRecord1)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 300, 180));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        lblMedicalRecord2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblMedicalRecord2.setText("Payment Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblMedicalRecord2)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedicalRecord2)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 310, 250));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        lblMedicalRecord.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblMedicalRecord.setText("Medical Record");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblMedicalRecord)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedicalRecord)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 300, 250));

        panelPersonalInformation.setBackground(new java.awt.Color(0, 153, 153));

        lblPersonalInformation.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblPersonalInformation.setText("Personal Information");

        lblPatientFirstName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblPatientFirstName.setText("First Name");

        lblPatientLastName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblPatientLastName.setText("Last Name");

        lblID.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblID.setText("ID");

        lblAge.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblAge.setText("Age");

        lblGender.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblGender.setText("Gender");

        lblPhoneNumber.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblPhoneNumber.setText("Phone Number");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblEmail.setText("Email");

        txtID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtPatientLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtPatientFirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtlAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        RbtMale.setBackground(new java.awt.Color(0, 153, 153));
        RbtMale.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        RbtMale.setText("Male");

        rbtFemale.setBackground(new java.awt.Color(0, 153, 153));
        rbtFemale.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        rbtFemale.setText("Female");

        javax.swing.GroupLayout panelPersonalInformationLayout = new javax.swing.GroupLayout(panelPersonalInformation);
        panelPersonalInformation.setLayout(panelPersonalInformationLayout);
        panelPersonalInformationLayout.setHorizontalGroup(
            panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblPatientLastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalInformationLayout.createSequentialGroup()
                                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtlAge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                        .addComponent(RbtMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtFemale))))))
                    .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblPersonalInformation)))
                .addContainerGap())
        );
        panelPersonalInformationLayout.setVerticalGroup(
            panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPersonalInformation)
                .addGap(13, 13, 13)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RbtMale, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(panelPersonalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 310, 250));

        btSearchBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/Search Logo.png"))); // NOI18N
        getContentPane().add(btSearchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 40, 40));

        lblSearchBox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblSearchBox.setForeground(new java.awt.Color(153, 153, 153));
        lblSearchBox.setText("Patient's Id");
        getContentPane().add(lblSearchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 130, 40));
        getContentPane().add(txtSearchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 360, 40));

        lblNoteMsg.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblNoteMsg.setText("Note : If you don't have any informatoin then fill none and zero for payment ");
        getContentPane().add(lblNoteMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        btAdd.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btAdd.setText("Add");
        getContentPane().add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 150, 50));

        btDelete.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 150, 50));

        btUpdate.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btUpdate.setText("Update");
        getContentPane().add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 150, 50));

        btClear.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        getContentPane().add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 150, 50));

        lblWelcomePageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/Background2.jpg"))); // NOI18N
        getContentPane().add(lblWelcomePageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageInformationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtMale;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSearchBox;
    private javax.swing.JButton btUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBangladeshHealthComplexMsg;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMedicalRecord;
    private javax.swing.JLabel lblMedicalRecord1;
    private javax.swing.JLabel lblMedicalRecord2;
    private javax.swing.JLabel lblNoteMsg;
    private javax.swing.JLabel lblPatientFirstName;
    private javax.swing.JLabel lblPatientLastName;
    private javax.swing.JLabel lblPersonalInformation;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSearchBox;
    private javax.swing.JLabel lblWelcomePageBackground;
    private javax.swing.JPanel panelPersonalInformation;
    private javax.swing.JRadioButton rbtFemale;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPatientFirstName;
    private javax.swing.JTextField txtPatientLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSearchBox;
    private javax.swing.JTextField txtlAge;
    // End of variables declaration//GEN-END:variables
}
