/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthComplex;

/**
 *
 * @author User
 */
public class ManageInformationPage extends javax.swing.JFrame {

    /**
     * Creates new form ManageInformationPage
     */
    public ManageInformationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblBangladeshHealthComplexMsg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMedicalRecord1 = new javax.swing.JLabel();
        lblOperationName = new javax.swing.JLabel();
        lblSurgeonsFirstName = new javax.swing.JLabel();
        lblSurgeonslastName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtOperationName = new javax.swing.JTextField();
        txtSurgeonFirstName = new javax.swing.JTextField();
        txtSurgeonLastName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblMedicalRecord2 = new javax.swing.JLabel();
        lblDoctorFees = new javax.swing.JLabel();
        lblMedicineFees = new javax.swing.JLabel();
        lblWardCost = new javax.swing.JLabel();
        lblOperationCost = new javax.swing.JLabel();
        lblPaidAmount = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        lblDueAmount = new javax.swing.JLabel();
        txtDoctorFees = new javax.swing.JTextField();
        txtMedicineFees = new javax.swing.JTextField();
        txtWardCost = new javax.swing.JTextField();
        txtOperationCost = new javax.swing.JTextField();
        txtPaidAmount = new javax.swing.JTextField();
        txtTotalCost = new javax.swing.JTextField();
        txtDueAmount = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblMedicalRecord = new javax.swing.JLabel();
        lblDoctorFirstName = new javax.swing.JLabel();
        lblDoctorLastName = new javax.swing.JLabel();
        lblProblem = new javax.swing.JLabel();
        lblMedicine = new javax.swing.JLabel();
        lblWardNo = new javax.swing.JLabel();
        txtDoctorFirstName = new javax.swing.JTextField();
        txtDoctorLastName = new javax.swing.JTextField();
        txtMedicine = new javax.swing.JTextField();
        txtProblem = new javax.swing.JTextField();
        txtWardNo = new javax.swing.JTextField();
        panelPersonalInformation = new javax.swing.JPanel();
        lblPersonalInformation = new javax.swing.JLabel();
        lblPatientFirstName = new javax.swing.JLabel();
        lblPatientLastName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPatientLastName = new javax.swing.JTextField();
        txtPatientFirstName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtlAge = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        RbtMale = new javax.swing.JRadioButton();
        rbtFemale = new javax.swing.JRadioButton();
        btSearchBox = new javax.swing.JButton();
        lblSearchBox = new javax.swing.JLabel();
        txtSearchBox = new javax.swing.JTextField();
        lblNoteMsg = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        lblWelcomePageBackground = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBangladeshHealthComplexMsg.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblBangladeshHealthComplexMsg.setText("Bangladesh Health Complex");
        getContentPane().add(lblBangladeshHealthComplexMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 600, 100));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblMedicalRecord1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblMedicalRecord1.setText("Operation Details");

        lblOperationName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblOperationName.setText("Operation Name");

        lblSurgeonsFirstName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblSurgeonsFirstName.setText("Surgeons First Name");

        lblSurgeonslastName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblSurgeonslastName.setText("Surgeons Last Name");

        lblDate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblDate.setText("Date");

        txtOperationName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtSurgeonFirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtSurgeonLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblMedicalRecord1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSurgeonslastName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSurgeonLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSurgeonsFirstName)
                                    .addComponent(lblOperationName))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOperationName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSurgeonFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedicalRecord1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperationName)
                    .addComponent(txtOperationName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurgeonsFirstName)
                    .addComponent(txtSurgeonFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurgeonslastName)
                    .addComponent(txtSurgeonLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 300, 180));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        lblMedicalRecord2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblMedicalRecord2.setText("Payment Details");

        lblDoctorFees.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblDoctorFees.setText("Doctor Fees");

        lblMedicineFees.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblMedicineFees.setText("Medicine Fees");

        lblWardCost.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblWardCost.setText("Ward Cost");

        lblOperationCost.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblOperationCost.setText("Operation Cost");

        lblPaidAmount.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblPaidAmount.setText("Paid Amount");

        lblTotalCost.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTotalCost.setText("Total Cost");

        lblDueAmount.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblDueAmount.setText("Due Amount");

        txtDoctorFees.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtMedicineFees.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtWardCost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtOperationCost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtPaidAmount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtTotalCost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtDueAmount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblMedicalRecord2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblOperationCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtOperationCost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblWardCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtWardCost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMedicineFees)
                                    .addComponent(lblDoctorFees))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMedicineFees, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtDoctorFees)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPaidAmount)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalCost)
                                    .addComponent(lblDueAmount))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDueAmount)
                                    .addComponent(txtTotalCost, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblMedicalRecord2)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorFees)
                    .addComponent(txtDoctorFees, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicineFees)
                    .addComponent(txtMedicineFees, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWardCost)
                    .addComponent(txtWardCost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperationCost)
                    .addComponent(txtOperationCost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaidAmount)
                    .addComponent(txtPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCost)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDueAmount)
                    .addComponent(txtDueAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 310, 260));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        lblMedicalRecord.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblMedicalRecord.setText("Medical Record");

        lblDoctorFirstName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblDoctorFirstName.setText("Doctors First Name");

        lblDoctorLastName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblDoctorLastName.setText("Doctors Last Name");

        lblProblem.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblProblem.setText("Problem");

        lblMedicine.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblMedicine.setText("Medicine");

        lblWardNo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblWardNo.setText("Ward No");

        txtDoctorFirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtDoctorLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtMedicine.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtProblem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtWardNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDoctorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDoctorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProblem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDoctorLastName)
                            .addComponent(txtDoctorFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtProblem)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblWardNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMedicine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(txtMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblMedicalRecord)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedicalRecord)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorFirstName)
                    .addComponent(txtDoctorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoctorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoctorLastName))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProblem)
                    .addComponent(txtProblem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicine)
                    .addComponent(txtMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWardNo)
                    .addComponent(txtWardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 300, 260));

        panelPersonalInformation.setBackground(new java.awt.Color(0, 153, 153));

        lblPersonalInformation.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblPersonalInformation.setText("Personal Information");

        lblPatientFirstName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblPatientFirstName.setText("First Name");

        lblPatientLastName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblPatientLastName.setText("Last Name");

        lblID.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblID.setText("ID");

        lblAge.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblAge.setText("Age");

        lblGender.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblGender.setText("Gender");

        lblPhoneNumber.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblPhoneNumber.setText("Phone Number");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblEmail.setText("Email");

        txtID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtPatientLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtPatientFirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtlAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        RbtMale.setBackground(new java.awt.Color(0, 153, 153));
        RbtMale.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        RbtMale.setText("Male");

        rbtFemale.setBackground(new java.awt.Color(0, 153, 153));
        rbtFemale.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        rbtFemale.setText("Female");

        javax.swing.GroupLayout panelPersonalInformationLayout = new javax.swing.GroupLayout(panelPersonalInformation);
        panelPersonalInformation.setLayout(panelPersonalInformationLayout);
        panelPersonalInformationLayout.setHorizontalGroup(
            panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblPatientLastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalInformationLayout.createSequentialGroup()
                                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RbtMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtFemale))
                                    .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(txtlAge))))))
                    .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalInformationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPersonalInformation)
                .addGap(38, 38, 38))
        );
        panelPersonalInformationLayout.setVerticalGroup(
            panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPersonalInformation)
                .addGap(13, 13, 13)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RbtMale, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelPersonalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 310, 260));

        btSearchBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/Search Logo.png"))); // NOI18N
        getContentPane().add(btSearchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 40, 40));

        lblSearchBox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblSearchBox.setForeground(new java.awt.Color(153, 153, 153));
        lblSearchBox.setText("Patient's Id");
        getContentPane().add(lblSearchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 130, 40));
        getContentPane().add(txtSearchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 360, 40));

        lblNoteMsg.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblNoteMsg.setText("Note : If you don't have any informatoin then fill none and zero for payment ");
        getContentPane().add(lblNoteMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        btAdd.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btAdd.setText("Add");
        getContentPane().add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 150, 50));

        btDelete.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 150, 50));

        btUpdate.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btUpdate.setText("Update");
        getContentPane().add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 150, 50));

        btClear.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        getContentPane().add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 150, 50));

        lblWelcomePageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/Background2.jpg"))); // NOI18N
        getContentPane().add(lblWelcomePageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageInformationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtMale;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSearchBox;
    private javax.swing.JButton btUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBangladeshHealthComplexMsg;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctorFees;
    private javax.swing.JLabel lblDoctorFirstName;
    private javax.swing.JLabel lblDoctorLastName;
    private javax.swing.JLabel lblDueAmount;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMedicalRecord;
    private javax.swing.JLabel lblMedicalRecord1;
    private javax.swing.JLabel lblMedicalRecord2;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblMedicineFees;
    private javax.swing.JLabel lblNoteMsg;
    private javax.swing.JLabel lblOperationCost;
    private javax.swing.JLabel lblOperationName;
    private javax.swing.JLabel lblPaidAmount;
    private javax.swing.JLabel lblPatientFirstName;
    private javax.swing.JLabel lblPatientLastName;
    private javax.swing.JLabel lblPersonalInformation;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblProblem;
    private javax.swing.JLabel lblSearchBox;
    private javax.swing.JLabel lblSurgeonsFirstName;
    private javax.swing.JLabel lblSurgeonslastName;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JLabel lblWardCost;
    private javax.swing.JLabel lblWardNo;
    private javax.swing.JLabel lblWelcomePageBackground;
    private javax.swing.JPanel panelPersonalInformation;
    private javax.swing.JRadioButton rbtFemale;
    private javax.swing.JTextField txtDoctorFees;
    private javax.swing.JTextField txtDoctorFirstName;
    private javax.swing.JTextField txtDoctorLastName;
    private javax.swing.JTextField txtDueAmount;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMedicine;
    private javax.swing.JTextField txtMedicineFees;
    private javax.swing.JTextField txtOperationCost;
    private javax.swing.JTextField txtOperationName;
    private javax.swing.JTextField txtPaidAmount;
    private javax.swing.JTextField txtPatientFirstName;
    private javax.swing.JTextField txtPatientLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtProblem;
    private javax.swing.JTextField txtSearchBox;
    private javax.swing.JTextField txtSurgeonFirstName;
    private javax.swing.JTextField txtSurgeonLastName;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JTextField txtWardCost;
    private javax.swing.JTextField txtWardNo;
    private javax.swing.JTextField txtlAge;
    // End of variables declaration//GEN-END:variables
}
