/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthComplex;

/**
 *
 * @author user
 */
public class PaymentDetailsPage extends javax.swing.JFrame {

    /**
     * Creates new form PaymentDetailsPage
     */
    public PaymentDetailsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBangladeshHealthComplexMsg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaymentlDetails = new javax.swing.JTable();
        panelTotalPaid = new javax.swing.JPanel();
        lblTotalPaidMsg = new javax.swing.JLabel();
        lblTotalPaid = new javax.swing.JLabel();
        panelTotalDue = new javax.swing.JPanel();
        lblTotalDueMsg = new javax.swing.JLabel();
        lblTotalDue = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        panelTotalPayable = new javax.swing.JPanel();
        lblTotalPayableMsg = new javax.swing.JLabel();
        lblTotalPayable = new javax.swing.JLabel();
        lblPaymentsDetailsMsg = new javax.swing.JLabel();
        lblPaymentDetailsLogo = new javax.swing.JLabel();
        lblWelcomePageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBangladeshHealthComplexMsg.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblBangladeshHealthComplexMsg.setText("Bangladesh Health Complex");
        getContentPane().add(lblBangladeshHealthComplexMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 0, 630, 82));

        tblPaymentlDetails.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        tblPaymentlDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient's Id", "Doctor Fees", "Medicine Fees", "Ward Cost", "Operation Cost", "Paid Ammount", "Total Cost", "Due Ammount"
            }
        ));
        jScrollPane1.setViewportView(tblPaymentlDetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 940, 250));

        panelTotalPaid.setBackground(new java.awt.Color(204, 0, 204));

        lblTotalPaidMsg.setBackground(new java.awt.Color(102, 0, 102));
        lblTotalPaidMsg.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTotalPaidMsg.setText("Total Paid");
        lblTotalPaidMsg.setOpaque(true);

        lblTotalPaid.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        javax.swing.GroupLayout panelTotalPaidLayout = new javax.swing.GroupLayout(panelTotalPaid);
        panelTotalPaid.setLayout(panelTotalPaidLayout);
        panelTotalPaidLayout.setHorizontalGroup(
            panelTotalPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalPaidMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(panelTotalPaidLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTotalPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTotalPaidLayout.setVerticalGroup(
            panelTotalPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPaidLayout.createSequentialGroup()
                .addComponent(lblTotalPaidMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(panelTotalPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 300, -1));

        panelTotalDue.setBackground(new java.awt.Color(255, 0, 51));

        lblTotalDueMsg.setBackground(new java.awt.Color(204, 0, 0));
        lblTotalDueMsg.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTotalDueMsg.setText("Total Due");
        lblTotalDueMsg.setOpaque(true);

        lblTotalDue.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        javax.swing.GroupLayout panelTotalDueLayout = new javax.swing.GroupLayout(panelTotalDue);
        panelTotalDue.setLayout(panelTotalDueLayout);
        panelTotalDueLayout.setHorizontalGroup(
            panelTotalDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalDueMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalDueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalDue, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelTotalDueLayout.setVerticalGroup(
            panelTotalDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalDueLayout.createSequentialGroup()
                .addComponent(lblTotalDueMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalDue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        getContentPane().add(panelTotalDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        btBack.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/back logo.png"))); // NOI18N
        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        getContentPane().add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 170, 50));

        panelTotalPayable.setBackground(new java.awt.Color(153, 153, 255));

        lblTotalPayableMsg.setBackground(new java.awt.Color(51, 51, 255));
        lblTotalPayableMsg.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTotalPayableMsg.setText("Total Payable");
        lblTotalPayableMsg.setOpaque(true);

        lblTotalPayable.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        javax.swing.GroupLayout panelTotalPayableLayout = new javax.swing.GroupLayout(panelTotalPayable);
        panelTotalPayable.setLayout(panelTotalPayableLayout);
        panelTotalPayableLayout.setHorizontalGroup(
            panelTotalPayableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalPayableMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalPayableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalPayable, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panelTotalPayableLayout.setVerticalGroup(
            panelTotalPayableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPayableLayout.createSequentialGroup()
                .addComponent(lblTotalPayableMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalPayable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        getContentPane().add(panelTotalPayable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblPaymentsDetailsMsg.setBackground(new java.awt.Color(255, 255, 255));
        lblPaymentsDetailsMsg.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblPaymentsDetailsMsg.setText("Payment Details of Patients");
        lblPaymentsDetailsMsg.setOpaque(true);
        getContentPane().add(lblPaymentsDetailsMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 590, 70));

        lblPaymentDetailsLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblPaymentDetailsLogo.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblPaymentDetailsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/payment details logo.png"))); // NOI18N
        lblPaymentDetailsLogo.setOpaque(true);
        getContentPane().add(lblPaymentDetailsLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, 70));

        lblWelcomePageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/Background2.jpg"))); // NOI18N
        getContentPane().add(lblWelcomePageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        setVisible(false);
        MenuPage m = new MenuPage();
        m.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentDetailsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBangladeshHealthComplexMsg;
    private javax.swing.JLabel lblPaymentDetailsLogo;
    private javax.swing.JLabel lblPaymentsDetailsMsg;
    private javax.swing.JLabel lblTotalDue;
    private javax.swing.JLabel lblTotalDueMsg;
    private javax.swing.JLabel lblTotalPaid;
    private javax.swing.JLabel lblTotalPaidMsg;
    private javax.swing.JLabel lblTotalPayable;
    private javax.swing.JLabel lblTotalPayableMsg;
    private javax.swing.JLabel lblWelcomePageBackground;
    private javax.swing.JPanel panelTotalDue;
    private javax.swing.JPanel panelTotalPaid;
    private javax.swing.JPanel panelTotalPayable;
    private javax.swing.JTable tblPaymentlDetails;
    // End of variables declaration//GEN-END:variables
}
