/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthComplex;

import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PersonalInfrmationPage extends javax.swing.JFrame {

    /**
     * Creates new form PersonalDetailsPage
     */
    public PersonalInfrmationPage() {
        initComponents();
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPersonaInformationMsg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonalInformation = new javax.swing.JTable();
        btBack = new javax.swing.JButton();
        lblBangladeshHealthComplexMsg1 = new javax.swing.JLabel();
        lblPersonalInformationLogo = new javax.swing.JLabel();
        lblWelcomePageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPersonaInformationMsg.setBackground(new java.awt.Color(255, 255, 255));
        lblPersonaInformationMsg.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblPersonaInformationMsg.setText("Personal Information of Patients");
        lblPersonaInformationMsg.setOpaque(true);
        getContentPane().add(lblPersonaInformationMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 660, 70));

        tblPersonalInformation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblPersonalInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient's Id", "Name", "Age", "Gender", "Phone Number", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblPersonalInformation);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 930, 310));

        btBack.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/back logo.png"))); // NOI18N
        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        getContentPane().add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 170, 50));

        lblBangladeshHealthComplexMsg1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblBangladeshHealthComplexMsg1.setText("Bangladesh Health Complex");
        getContentPane().add(lblBangladeshHealthComplexMsg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 630, 100));

        lblPersonalInformationLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblPersonalInformationLogo.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblPersonalInformationLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/personal information logo.png"))); // NOI18N
        lblPersonalInformationLogo.setOpaque(true);
        getContentPane().add(lblPersonalInformationLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, 70));

        lblWelcomePageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthComplex/Background2.jpg"))); // NOI18N
        getContentPane().add(lblWelcomePageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        setVisible(false);
        MenuPage m = new MenuPage();
        m.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalInfrmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalInfrmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalInfrmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalInfrmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalInfrmationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBangladeshHealthComplexMsg1;
    private javax.swing.JLabel lblPersonaInformationMsg;
    private javax.swing.JLabel lblPersonalInformationLogo;
    private javax.swing.JLabel lblWelcomePageBackground;
    private javax.swing.JTable tblPersonalInformation;
    // End of variables declaration//GEN-END:variables
}
